// Auto-generated by LibreLane
module hw_scheduler_top(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input rst_n,
  input sclk,
  input cs_n,
  input mosi,
  output miso,
  input[7:0] ext_irq,
  output irq_n,
  input scan_en,
  input scan_in,
  output scan_out
);
endmodule
